DECLARE
tbl_count number;
sql_stmt long;

BEGIN
--CUSTOMER
    SELECT COUNT(*) INTO tbl_count 
    FROM dba_tables
    WHERE owner = 'SYSTEM'
    AND table_name = 'CUSTOMER';

    IF(tbl_count <= 0)
        THEN
        sql_stmt:='
        CREATE TABLE CUSTOMER (
            ID_CUSTOMER NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            NAME_CUSTOMER VARCHAR2(25) NOT NULL,
            ADDRESS_CUSTOMER VARCHAR2(200),
            CELLPHONE_CUSTOMER NUMBER(20),
            USERNAME_CUSTOMER VARCHAR2(30),
            PASSWORD_CUSTOMER VARCHAR2(150),
            BRITHDAY_CUSTOMER DATE,
            EMAIL_CUSTOMER VARCHAR2(100),
            STATUS_CUSTOMER VARCHAR2(2),
            PRIMARY KEY(ID_CUSTOMER)
        )';
        EXECUTE IMMEDIATE sql_stmt;
    END IF;
--SUPPLIER
    SELECT COUNT(*) INTO tbl_count 
    FROM dba_tables
    WHERE owner = 'SYSTEM'
    AND table_name = 'SUPPLIER';

    IF(tbl_count <= 0)
        THEN
        sql_stmt:='
        CREATE TABLE SUPPLIER (
            ID_SUPPLIER NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            NAME_SUPPLIER VARCHAR2(25) NOT NULL,
            ADDRESS_SUPPLIER VARCHAR2(200),
            CELLPHONE_SUPPLIER NUMBER(20),
            STATUS_SUPPLIER VARCHAR2(2),
            PRIMARY KEY(ID_SUPPLIER)
        )';
        EXECUTE IMMEDIATE sql_stmt;
    END IF;
--PRODUCT_CATEGORY
SELECT COUNT(*) INTO tbl_count 
    FROM dba_tables
    WHERE owner = 'SYSTEM'
    AND table_name = 'PRODUCT_CATEGORY';

    IF(tbl_count <= 0)
        THEN
        sql_stmt:='
        CREATE TABLE PRODUCT_CATEGORY (
            ID_PRODUCT_CATEGORY NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            NAME_PRODUCT_CATEGORY VARCHAR2(25) NOT NULL,
            STATUS_PRODUCT_CATEGORY VARCHAR2(2),
            PRIMARY KEY(ID_PRODUCT_CATEGORY)
        )';
        EXECUTE IMMEDIATE sql_stmt;
    END IF;
--PRODUCT
SELECT COUNT(*) INTO tbl_count 
    FROM dba_tables
    WHERE owner = 'SYSTEM'
    AND table_name = 'PRODUCT';

    IF(tbl_count <= 0)
        THEN
        sql_stmt:='
        CREATE TABLE PRODUCT (
            ID_PRODUCT NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            NAME_PRODUCT VARCHAR2(25) NOT NULL,
            DESCRIPTION_PRODUCT VARCHAR2(200),
            IMPORT_PRICE_PRODUCT NUMBER(22,2),
            EXPORT_PRICE_PRODUCT NUMBER(22,2),
            IMAGE_PRODUCT VARCHAR2(200),
            ID_PRODUCT_CATEGORY NUMBER(10),
            ID_SUPPLIER NUMBER(10),
            QUANTITY_PRODUCT NUMBER(10),
            STATUS_PRODUCT VARCHAR2(2),
            PRIMARY KEY(ID_PRODUCT),
            CONSTRAINT FK_ID_PRODUCT_CATEGORY FOREIGN KEY(ID_PRODUCT_CATEGORY) REFERENCES PRODUCT_CATEGORY(ID_PRODUCT_CATEGORY),
            CONSTRAINT FK_ID_SUPPLIER FOREIGN KEY(ID_SUPPLIER) REFERENCES SUPPLIER(ID_SUPPLIER)
        )';
        EXECUTE IMMEDIATE sql_stmt;
    END IF;
--BILL
SELECT COUNT(*) INTO tbl_count 
    FROM dba_tables
    WHERE owner = 'SYSTEM'
    AND table_name = 'BILL';

    IF(tbl_count <= 0)
        THEN
        sql_stmt:='
        CREATE TABLE BILL (
            ID_BILL NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            ORDER_DATE DATE,
            DELIVERY_DATE DATE,
            ID_CUSTOMER NUMBER(10),
            PRICE NUMBER(22,2),
            STATUS_ID_BILL VARCHAR2(2),
            PRIMARY KEY(ID_BILL),
            CONSTRAINT FK_ID_CUSTOMER FOREIGN KEY(ID_CUSTOMER) REFERENCES CUSTOMER(ID_CUSTOMER)
        )';
        EXECUTE IMMEDIATE sql_stmt;
    END IF;
--BILL_DETAILS
SELECT COUNT(*) INTO tbl_count 
    FROM dba_tables
    WHERE owner = 'SYSTEM'
    AND table_name = 'BILL_DETAILS';

    IF(tbl_count <= 0)
        THEN
        sql_stmt:='
        CREATE TABLE BILL_DETAILS (
            ID_BILL_DETAILS NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            ID_BILL NUMBER(10),
            ID_PRODUCT NUMBER(10),
            QUANTITY NUMBER(10),
            PRICE NUMBER(22,2),
            STATUS_BILL_DETAILS VARCHAR2(2),
            PRIMARY KEY(ID_BILL_DETAILS),
            CONSTRAINT FK_ID_BILL FOREIGN KEY(ID_BILL) REFERENCES BILL(ID_BILL),
            CONSTRAINT FK_ID_PRODUCT FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
        )';
        EXECUTE IMMEDIATE sql_stmt;
    END IF;

END;